# Applications list
INSTALLED_APPS = [
    'corsheaders',
    'sslserver',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',  # aws s3
    # api
    'rest_framework',
    'rest_framework_api_key',
    'rest_framework.authtoken',
    'saas_core',
    'authentication',
    'categories',
    'locations',
    'feedback',
    'messaging',
    'notifications',
    'payments',
    'public_configs',
    'services',
    'seeks',
    'tags',
    'votes',
    'feed',
    'fb_ads',
    # 'api',
    # auth
    'oauth2_provider',
    'social_django',
    'rest_framework_social_oauth2',
    'rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'allauth.socialaccount',
    # 'allauth.socialaccount.providers.facebook',
    # 'allauth.socialaccount.providers.twitter',
    # tasks
    # 'celery',
    'colorfield',
    'djmoney',
    'import_export',
    # realtime
    'channels',
    # email templates
    'mjml',
    'debug_toolbar',
    'django_filters',
]
